name: pos_samurai
version: 1.0.0
environment: {sdk: ">=3.0.0 <4.0.0"}
dependencies:
  flutter: {sdk: flutter}
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.0
  shared_preferences: ^2.2.2
  mobile_scanner: ^4.0.0
dev_dependencies:
  flutter_test: {sdk: flutter}
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
flutter: {uses-material-design: true}


